import pandas as pd

csv1 = pd.read_csv('F:\\数据\\GPX4\\GPX4_500.csv',header=0)
# csv1 = pd.read_csv('F:/BaiduNetdiskDownload/export2000_shuxing.csv')

sheet1 = pd.DataFrame(csv1)
# sheet2 = pd.DataFrame(csv2)
len1 = len(sheet1)
# str1 = sheet1.loc[1,'frameInfo'].replace('[','')
# str1 = sheet1.loc[1,'frameInfo'].replace(']','')
# str1 = sheet1.loc[1,'frameInfo'].replace('\\n,','\n')
for i in range(len1):
    # sheet1.loc[i, 'spheres'] = sheet1.loc[i, 'spheres'].replace('\'', '')
    sheet1.loc[i, 'residueID'] = sheet1.loc[i, 'residueID'].replace('\'', '')
    sheet1.loc[i, 'residueID'] = sheet1.loc[i, 'residueID'].replace('{', '[')
    sheet1.loc[i, 'residueID'] = sheet1.loc[i, 'residueID'].replace('}', ']')
    sheet1.loc[i,'frame_pocket'] = sheet1.loc[i,'frame_pocket'].replace('frame_pocket','')
    sheet1.loc[i, 'frameInfo'] = sheet1.loc[i, 'frameInfo'].replace('[', '')
    sheet1.loc[i, 'frameInfo'] = sheet1.loc[i, 'frameInfo'].replace(']', '')
    sheet1.loc[i, 'frameInfo'] = sheet1.loc[i, 'frameInfo'].replace('\\n', '\n')
    sheet1.loc[i, 'frameInfo'] = sheet1.loc[i, 'frameInfo'].replace(', ', '')
    sheet1.loc[i, 'frameInfo'] = sheet1.loc[i, 'frameInfo'].replace('\'', '')
    sheet1.loc[i, 'pocketInfo'] = sheet1.loc[i, 'pocketInfo'].replace('[', '')
    sheet1.loc[i, 'pocketInfo'] = sheet1.loc[i, 'pocketInfo'].replace(']', '')
    sheet1.loc[i, 'pocketInfo'] = sheet1.loc[i, 'pocketInfo'].replace('\'', '')
    sheet1.loc[i, 'pocketInfo'] = sheet1.loc[i, 'pocketInfo'].replace('\\n', '\n')
    sheet1.loc[i, 'pocketInfo'] = sheet1.loc[i, 'pocketInfo'].replace(', ', '')
# print(sheet1.loc[2, 'frameInfo'])
sheet1.to_csv('F:\\数据\\GPX4\\GPX4_1000_surface.csv',index=None)
# sheet1.to_csv('GPX4_2000_POCKET.csv',index=None)
